trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'
  name: Local

steps:
- script: |
    echo '$(System.DefaultWorkingDirectory)/terraform'
    terraform init
  displayName: 'Terraform Init'

- script: |
    echo '$(System.DefaultWorkingDirectory)/terraform'
    terraform plan
  displayName: 'Terraform Plan'

- script: |
    echo '$(System.DefaultWorkingDirectory)/terraform'
    terraform apply -auto-approve
  displayName: 'Terraform AKS Deployment'
