resource_group_name = "tech-challenge"
location            = "East US"
cluster_name        = "tech-challengeaks-cluster"
dns_prefix          = "aks"
subscription_id     = "f0a8e34c-95a1-4f03-abff-8fd192d2cd42"  
