name: Terraform-AKS-Deployment

on:
  pull_request:
    types: [assigned]
  push:
    branches: [ "main" ]

env:
  working-directory: infra_terraform
  ARM_CLIENT_ID: ${{secrets.TF_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.TF_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.TF_TENANT_ID}}
  RESOURCE_GROUP: "tech-challenge-rg"
  CLUSTER_NAME: "tech-challenge-aks-cluster"

permissions:
  id-token: write
  contents: read
  
jobs:          
  setup-terraform:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    
    - name: Terraform Fmt
      id: fmt
      run: terraform fmt -check
      working-directory: ${{env.working-directory}}
    
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{env.working-directory}}

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ${{env.working-directory}}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: ${{env.working-directory}}

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      working-directory: ${{env.working-directory}}

    - name: Terraform Output
      id: output
      run: | 
       terraform output kube_config > kubeconfig
       mkdir -p $HOME/.kube
       mv kubeconfig $HOME/.kube/config