name: Terraform-AKS-Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read
  
jobs:          
  setup-terraform:
    runs-on: ubuntu-latest
    env:
      working-directory: infra_terraform
      ARM_CLIENT_ID: ${{secrets.TF_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_TENANT_ID}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ env.working-directory }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: ${{ env.working-directory }}

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: ${{ env.working-directory }}

    - name: Save Outputs
      run: |
        echo "::set-output name=cluster_name::$(terraform output cluster_name)"
      id: terraform_outputs

    - name: Upload Terraform state
      uses: actions/upload-artifact@v2
      with:
        name: terraform-state
        path: .terraform

  conect-azure-devops:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/group2-soat1/tech-challenge'
        azure-pipeline-name: 'Pos-Tech-Fiap-Group-2.infra-tech-challenge-k8s'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
